# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: crypto123
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: crypto
      MYSQL_USER: maxi
      MYSQL_PASSWORD: crypto123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  # pm2:
  #   build: .
  #   image: crpyto-pm2
  #   ports:
  #     - 8000:8000