CREATE TABLE rates(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_currency INT UNSIGNED NOT NULL,
    value FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE rates
ADD CONSTRAINT FK_Rate_Currency
FOREIGN KEY (id_currency) REFERENCES currencies(id);

INSERT INTO rates(id_currency, value)
VALUES
(1, 11924.231233),
(2, 308.313553),
(3, 0.0990881)